"""empty message

Revision ID: 2b0fb5d21738
Revises: f97e2f1d8e33
Create Date: 2020-09-03 10:23:33.773837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b0fb5d21738'
down_revision = 'f97e2f1d8e33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token', 'access_token',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('token', 'refresh_token',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('token', 'used',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('token', 'user_client_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=254),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user_client', 'user_agent',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user_client', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_client', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('user_client', 'user_agent',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=254),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('token', 'user_client_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('token', 'used',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('token', 'refresh_token',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('token', 'access_token',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
