"""empty message

Revision ID: 624d8e05b274
Revises: 0aedc9ebe86e
Create Date: 2020-09-02 19:08:25.128458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624d8e05b274'
down_revision = '0aedc9ebe86e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_client', ['user_agent', 'user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_client', type_='unique')
    # ### end Alembic commands ###
