"""empty message

Revision ID: f97e2f1d8e33
Revises: 624d8e05b274
Create Date: 2020-09-03 10:07:00.262228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f97e2f1d8e33'
down_revision = '624d8e05b274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('used', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'used')
    # ### end Alembic commands ###
